### ISSUE TITLE
[FEATURE] `add_*` methods in the python SDK

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3998]
**Is your feature request related to a problem? Please describe.**
Once a dataset is created, it is not possible to add fields or questions, but one can add metadata properties. 

**Describe the solution you'd like**
Align the SDK API with more `add_*` methods.

**Comment by nataliaElv** [comment]
Adding fields and questions have serious implications for a dataset down the line. We should discuss this further before implementing this solution.

**Comment by dvsrepo** [comment]
As discussed, updating questions, fields, and guidelines should be possible when there are no records in the dataset. Related to this is how to extend/tune a dataset created from a task template.

**Comment by davidberenstein1957** [comment]
@nataliaElv, I think this was resolved partially with the communication here? https://github.com/argilla-io/argilla/issues/4080

**Comment by nataliaElv** [comment]
Not really. It's still not possible to add fields, questions, etc. after a dataset has been pushed to Argilla. This needs to be aligned with `metadata_properties`, which is the only setting that has an `add_*` method right now.
